export {default as Car1} from './img/car-1.jpg'
export {default as Car2} from './img/car-2.jpg'
export {default as Car3} from './img/car-3.jpg'
export {default as Car4} from './img/car-4.jpg'
export {default as Car5} from './img/car-5.jpg'
export {default as PricingBg} from './img/Pricing.webp'